engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      #rulesets: ".phpmd.xml"

  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"

  duplication:
    enabled: true
    config:
      languages:
      - php:

ratings:
  paths:
  - "src/**.php"
